version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install --force --legacy-peer-deps
      - npm install typescript --save-dev --force --legacy-peer-deps
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: dist
