version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Сброс NODE_ENV, чтобы установить devDependencies"
      - export NODE_ENV=
      - echo "Устанавливаем все зависимости"
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Building..."
      - npm run build

  post_build:
    commands:
      - echo "Done on `date`"

artifacts:
  base-directory: dist
  files:
    - "**/*"
