version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing NPM dependencies cleanly...
      - npm install
      - npm install vite --save-dev

  build:
    commands:
      - echo Build started on `date`
      - npx tsc
      - npx vite build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: dist
