version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
      - npm install -g typescript
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: dist
