version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing deps (incl. devDependencies)..."
      - export NODE_ENV=
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Building..."
      - npm run build

  post_build:
    commands:
      - echo "Deploy done on `date`"
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E248SP1JNJWCHR --paths "/*"
      - echo "Invalidation requested."

artifacts:
  base-directory: dist
  files:
    - "**/*"
